---
#
# This file can contain any ansible or commands that may be wanted to run
# from the undercloud.
#
- name: Run External Upgrade Step Tasks
  debug:
    msg: >-
      This is an example of an external upgrade task execution which is
      run on the undercloud.
